[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "AnimeTime"
version = "0.1"
authors = [
 {name="Arthur276", email="arthur.cott@free.fr"}
]
description = "Un package pour gérer ses animés facilement"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependecies = ["AnimeData"]
[project.urls]
"Homepage" = "https://github.com/Arthur276/AnimeTime"
"Bug Tracker" = "https://github.com/Arthur276/AnimeTime/issues"
